var string1 = "hello";
var string2 = "world";
console.log("Is string1 == 'hello'? ");
console.log(string1 == "hello");
console.log("\nIs string2 != 'hello'?");
console.log(string2 != "hello");
var text = "Hello World";
console.log("\nIs text.toLowerCase() == 'hello world'? I predict True.");
console.log(text.toLowerCase() == "hello world");
var num1 = 10;
var num2 = 5;
console.log("\nIs num1 > num2? True.");
console.log(num1 > num2);
console.log("\nIs num1 < num2? False.");
console.log(num1 < num2);
console.log("\nIs num1 >= num2? True.");
console.log(num1 >= num2);
console.log("\nIs num1 <= num2? False.");
console.log(num1 <= num2);
var x = 10;
var y = 20;
var z = 30;
console.log("\nIs x < y and y < z? .");
console.log(x < y && y < z);
console.log("\nIs x < y or y > z? ");
console.log(x < y || y > z);
var fruitss = ["apple", "banana", "orange"];
console.log("\nIs 'apple' in fruits? ");
console.log(fruitss.indexOf("apple"));
console.log("\nIs 'grape' not in fruits?");
console.log(!fruitss.indexOf("grape"));
