let places: string[] = ["Pakistan", "Paris", "Palestine", "Canada", "India"];
console.log("Original order:", places);
console.log("Alphabetical order:", [...places].sort());
console.log("Still in original order:", places);
console.log("Reverse alphabetical order:", [...places].sort().reverse());
console.log("Still in original order:", places);
places.reverse();
console.log("Reversed order:", places);
places.reverse();
console.log("Back to original order:", places);
places.sort();
console.log("Sorted in alphabetical order:", places);
places.sort((a, b) => b.localeCompare(a));
console.log("Sorted in reverse alphabetical order:", places);